# 29.274 f60

#
#

mtypes = {
0 : 'Reserved',
1 : 'Echo Request',
2 : 'Echo Response',
3 : 'Version Not Supported Indication',
4 : '..',
5 : '..',
6 : '..',
7 : '..',
8 : '..',
9 : '..',
10 : '..',
11 : '..',
12 : '..',
13 : '..',
14 : '..',
15 : '..',
16 : '..',
17 : '..',
18 : '..',
19 : '..',
20 : '..',
21 : '..',
22 : '..',
23 : '..',
24 : '..',
25 : '..',
26 : '..',
27 : '..',
28 : '..',
29 : '..',
30 : '..',
31 : '..',
32 : 'Create Session Request',
33 : 'Create Session Response',
34 : '..',
35 : '..',
36 : 'Delete Session Request',
37 : 'Delete Session Response',
38 : 'Change Notification Request',
39 : 'Change Notification Response',
40 : 'Remote UE Report Notification',
41 : 'Remote UE Report Acknowledge',
42 : 'For future use',
43 : 'For future use',
44 : 'For future use',
45 : 'For future use',
46 : 'For future use',
47 : 'For future use',
48 : 'For future use',
49 : 'For future use',
50 : 'For future use',
51 : 'For future use',
52 : 'For future use',
53 : 'For future use',
54 : 'For future use',
55 : 'For future use',
56 : 'For future use',
57 : 'For future use',
58 : 'For future use',
59 : 'For future use',
60 : 'For future use',
61 : 'For future use',
62 : 'For future use',
63 : 'For future use',
64 : 'Modify Bearer Command',
65 : 'Modify Bearer Failure Indication',
66 : 'Delete Bearer Command',
67 : 'Delete Bearer Failure Indication',
68 : 'Bearer Resource Command',
69 : 'Bearer Resource Failure Indication',
70 : 'Downlink Data Notification Failure Indication',
71 : 'Trace Session Activation',
72 : 'Trace Session Deactivation',
73 : 'Stop Paging Indication',
74 : 'For future use',
75 : 'For future use',
76 : 'For future use',
77 : 'For future use',
78 : 'For future use',
79 : 'For future use',
80 : 'For future use',
81 : 'For future use',
82 : 'For future use',
83 : 'For future use',
84 : 'For future use',
85 : 'For future use',
86 : 'For future use',
87 : 'For future use',
88 : 'For future use',
89 : 'For future use',
90 : 'For future use',
91 : 'For future use',
92 : 'For future use',
93 : 'For future use',
94 : 'For future use',
95 : 'Create Bearer Request',
96 : 'Create Bearer Response',
97 : 'Update Bearer Request',
98 : 'Update Bearer Response',
99 : 'Delete Bearer Request',
100 : 'Delete Bearer Response',
101 : 'Delete PDN Connection Set Request',
102 : 'Delete PDN Connection Set Response',
103 : 'PGW Downlink Triggering Notification',
104 : 'PGW Downlink Triggering Acknowledge',
105 : 'For future use',
106 : 'For future use',
107 : 'For future use',
108 : 'For future use',
109 : 'For future use',
110 : 'For future use',
111 : 'For future use',
112 : 'For future use',
113 : 'For future use',
114 : 'For future use',
115 : 'For future use',
116 : 'For future use',
117 : 'For future use',
118 : 'For future use',
119 : 'For future use',
120 : 'For future use',
121 : 'For future use',
122 : 'For future use',
123 : 'For future use',
124 : 'For future use',
125 : 'For future use',
126 : 'For future use',
127 : 'For future use',
128 : 'Identification Request',
129 : 'Identification Response',
130 : 'Context Request',
131 : 'Context Response',
132 : 'Context Acknowledge',
133 : 'Forward Relocation Request',
134 : 'Forward Relocation Response',
135 : 'Forward Relocation Complete Notification',
136 : 'Forward Relocation Complete Acknowledge',
137 : 'Forward Access Context Notification',
138 : 'Forward Access Context Acknowledge',
139 : 'Forward Access Context Acknowledge',
140 : 'Relocation Cancel Response',
141 : 'Configuration Transfer Tunnel',
142 : 'For future use',
143 : 'For future use',
144 : 'For future use',
145 : 'For future use',
146 : 'For future use',
147 : 'For future use',
148 : 'For future use',
149 : 'Detach Notification',
150 : 'Detach Acknowledge',
151 : 'CS Paging Indication',
152 : 'RAN Information Relay',
153 : 'Alert MME Notification',
154 : 'Alert MME Acknowledge',
155 : 'UE Activity Notification',
156 : 'UE Activity Acknowledge',
157 : 'ISR Status Indication',
158 : 'UE Registration Query Request',
159 : 'UE Registration Query Response',
160 : 'Create Forwarding Tunnel Request',
161 : 'Create Forwarding Tunnel Response',
162 : 'Suspend Notification',
163 : 'Suspend Acknowledge',
164 : 'Resume Notification',
165 : 'Resume Acknowledge',
166 : 'Create Indirect Data Forwarding Tunnel Request',
167 : 'Create Indirect Data Forwarding Tunnel Response',
168 : 'Delete Indirect Data Forwarding Tunnel Request',
169 : 'Delete Indirect Data Forwarding Tunnel Response',
170 : 'Release Access Bearers Request',
171 : 'Release Access Bearers Response',
172 : 'For future use',
173 : 'For future use',
174 : 'For future use',
175 : 'For future use',
176 : 'Downlink Data Notification',
177 : 'Downlink Data Notification Acknowledge',
178 : 'Reserved. Allocated in earlier version of the specification.',
179 : 'PGW Restart Notification',
180 : 'PGW Restart Notification Acknowledge',
181 : 'For future use',
182 : 'For future use',
183 : 'For future use',
184 : 'For future use',
185 : 'For future use',
186 : 'For future use',
187 : 'For future use',
188 : 'For future use',
189 : 'For future use',
190 : 'For future use',
191 : 'For future use',
192 : 'For future use',
193 : 'For future use',
194 : 'For future use',
195 : 'For future use',
196 : 'For future use',
197 : 'For future use',
198 : 'For future use',
199 : 'For future use',
200 : 'Update PDN Connection Set Request',
201 : 'Update PDN Connection Set Response',
202 : 'For future use',
203 : 'For future use',
204 : 'For future use',
205 : 'For future use',
206 : 'For future use',
207 : 'For future use',
208 : 'For future use',
209 : 'For future use',
210 : 'For future use',
211 : 'Modify Access Bearers Request',
212 : 'Modify Access Bearers Response',
213 : 'For future use',
214 : 'For future use',
215 : 'For future use',
216 : 'For future use',
217 : 'For future use',
218 : 'For future use',
219 : 'For future use',
220 : 'For future use',
221 : 'For future use',
222 : 'For future use',
223 : 'For future use',
224 : 'For future use',
225 : 'For future use',
226 : 'For future use',
227 : 'For future use',
228 : 'For future use',
229 : 'For future use',
230 : 'For future use',
231 : 'MBMS Session Start Request',
232 : 'MBMS Session Start Response',
233 : 'MBMS Session Update Request',
234 : 'MBMS Session Update Response',
235 : 'MBMS Session Stop Request',
236 : 'MBMS Session Stop Response',
237 : 'For future use',
238 : 'For future use',
239 : 'For future use',
240 : '..',
241 : '..',
242 : '..',
243 : '..',
244 : '..',
245 : '..',
246 : '..',
247 : '..',
248 : 'For future use',
249 : 'For future use',
250 : 'For future use',
251 : 'For future use',
252 : 'For future use',
253 : 'For future use',
254 : 'For future use',
255 : 'For future use',
}
